backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "src/assets" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/BlogPost.astro"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "publishDate", widget: "datetime", required: false}
      - {label: "Hero Image", name: "heroImage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Slug", name: "slug", widget: "string", required: false} # Optional: Slug for the post
      - {label: "Featured", name: "featured", widget: "boolean", required: false} # Optional: Display post in featured section
      - {label: "Tags", name: "tags", widget: "list", required: false} # Optional: Related keywords for the post
      - {label: "OG Image", name: "ogImage", widget: "image", required: false} # Optional: OG image for social media sharing
      - {label: "Canonical URL", name: "canonicalURL", widget: "string", required: false} # Optional: Canonical URL for the post